### ISSUE TITLE
UTF-8 Encoding issue

### ISSUE THREAD

**Issue by Nussbutter** [ggpwnkthx/Microsoft-Graph-SMTP-Relay#6]
Attempted to use this with SSRS and it works but the report attachments are mangled and renamed. The file contains the correct data but the filename removes the extension. 

You can see the log here the MAIL FROM line appends "BODY=8BITMIME SMTPUTF8"

> INFO:mail.log:('xxx.xxx.xxx.xxx', 51714) >> b'*REDACTED*'
> INFO:mail.log:('xxx.xxx.xxx.xxx', 51714) >> b'MAIL FROM:<noreply@*REDACTED*> **_BODY=8BITMIME SMTPUTF8'_**
> INFO:mail.log:('xxx.xxx.xxx.xxx', 51714) sender: noreply@*REDACTED*
> INFO:mail.log:('xxx.xxx.xxx.xxx', 51714) >> b'RCPT TO:<ME@*REDACTED*>'
> INFO:mail.log:('xxx.xxx.xxx.xxx', 51714) recip: ME@*REDACTED*

Here is what the attachment looks like in outlook
> ![image](https://github.com/user-attachments/assets/6c57bea1-02c6-4c3f-bfb5-ee0a00d4b8d0)

Ran the name through Base64 decoder and it looks like the name is encoded. 
> ![image](https://github.com/user-attachments/assets/279171df-60ac-40aa-b403-c71e4257d264)

Is there any way you can get this to support this format? Using it on SSRS would be fantastic.

**Comment by Nussbutter** [comment]
Thank you for looking into this!

Unfortunately no luck after the update. The filename still comes in as "=?utf-8?B?VEVTVC5jc3Y=?=" which should decode to Test.csv
<img width="300" alt="image" src="https://github.com/user-attachments/assets/a1c96f82-1d5c-47f5-87a0-5e6d3caf89e5">

**Comment by ggpwnkthx** [comment]
I added a non-inline attachment test and it appears to be working on my end.

![image](https://github.com/user-attachments/assets/55b5bab7-ca88-4c19-98ed-c4bc9034c589)

I'm going to mark this issue as closed, but let me know if you're still having issues.

**Comment by ggpwnkthx** [comment]
Reopening because the committed change is not a comprehensive solution.

**Comment by ggpwnkthx** [comment]
@Nussbutter, I've pushed an update that covers RFC2047 and RFC2231. It can also be pretty easily extended for other encodings. I'm not super thrilled with the code, but it should get you rolling.

**Comment by Nussbutter** [comment]
Awesome, it's working now. Thank you!
